"""Configure build of Sphinx documentation for textnets."""

# textnets documentation build configuration file, created by
# sphinx-quickstart on Fri Jun  9 13:47:02 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another
# directory, add these directories to sys.path here. If the directory is
# relative to the documentation root, use os.path.abspath to make it
# absolute, like shown here.

import os
import sys
from pathlib import Path

sys.path.insert(0, Path("..").resolve())

import textnets

# -- General configuration ---------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.viewcode",
    "sphinx.ext.napoleon",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.autosectionlabel",
    "sphinxcontrib.bibtex",
    "jupyter_sphinx",
]

autosummary_generate = True
autodoc_inherit_docstrings = True
autoclass_content = "both"
napoleon_numpy_docstring = True

intersphinx_mapping = {
    "ig": ("https://igraph.org/python/api/latest/", None),
    "la": ("https://leidenalg.readthedocs.io/en/stable/", None),
    "mp": ("https://matplotlib.org/stable/", None),
    "np": ("https://numpy.org/doc/stable/", None),
    "pd": ("https://pandas.pydata.org/docs/", None),
    "py": ("https://docs.python.org/3", None),
}

bibtex_bibfiles = ["refs.bib"]
bibtex_reference_style = "author_year"

jupyter_sphinx_thebelab_config = {
    "requestKernel": True,
    "binderOptions": {"repo": "jboynyc/textnets-binder", "ref": "trunk"},
}

todo_include_todos = not os.environ.get("READTHEDOCS")

default_role = "any"

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "textnets"
copyright = "&copy; 2025"
author = "John D. Boy"

# The version info for the project you're documenting, acts as replacement
# for |version| and |release|, also used in various other places throughout
# the built documents.
#
# The short X.Y version.
version = textnets.__version__
# The full version, including alpha/beta/rc tags.
release = version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "bw"

# -- Options for HTML output -------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "shibuya"
html_theme_options = {
    "accent_color": "lime",
    "github_url": "https://github.com/jboynyc/textnets",
    "mastodon_url": "https://post.lurk.org/@jboy",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

html_logo = "_static/textnets-logo.svg"

# -- Options for HTMLHelp output ---------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "textnetsdoc"
